# Project Three, Part One: Cozy Fantasy Dataset Cleaning

In [1]:
%pip install praw --quiet

Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install pytrends --quiet

Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import requests
import altair as alt
import praw
import pytrends

print("libraries ready")

libraries ready

In [4]:
from dotenv import load_dotenv
import os

load_dotenv()
API_KEY = os.getenv("GOOGLE_BOOKS_API_KEY")

In [5]:
#adding a time loop because I was getting 503 errors

import time

def search_google_books(title, author, max_retries=3):
    query = f"intitle:{title} inauthor:{author}"
    url = "https://www.googleapis.com/books/v1/volumes"
    params = {"q": query, "key": API_KEY}

    for attempt in range(max_retries):
        response = requests.get(url, params=params)
        data = response.json()
        if "error" not in data:
            return data
        if data["error"].get("code") == 503:
            time.sleep(2 * (attempt + 1)) 
            continue
        return data  

    return data

In [6]:
result = search_google_books("Legends & Lattes", "Travis Baldree")
result

{'kind': 'books#volumes',
 'totalItems': 300,
 'items': [{'kind': 'books#volume',
   'id': '7lJzEAAAQBAJ',
   'etag': '9WzB4PW3gME',
   'selfLink': 'https://www.googleapis.com/books/v1/volumes/7lJzEAAAQBAJ',
   'volumeInfo': {'title': 'Legends & Lattes',
    'subtitle': 'A Novel of High Fantasy and Low Stakes',
    'authors': ['Travis Baldree'],
    'publisher': 'Tor Books',
    'publishedDate': '2022-06-07',
    'description': "An Instant New York Times Bestseller A Barnes & Noble Best Book of 2022 A Library Reads Pick An Indie Next Pick A Goodreads Best Fantasy Choice Award Nominee The much-beloved BookTok sensation, Travis Baldree's novel of high fantasy and low stakes. *This new edition includes a very special, never-before-seen bonus story, 'Pages to Fill.'* After a lifetime of bounties and bloodshed, Viv is hanging up her sword for the last time. The battle-weary orc aims to start fresh, opening the first ever coffee shop in the city of Thune. But old and new rivals stand in the way of success — not to mention the fact that no one has the faintest idea what coffee actually is. If Viv wants to put the blade behind her and make her plans a reality, she won't be able to go it alone. But the true rewards of the uncharted path are the travelers you meet along the way. And whether drawn together by ancient magic, flaky pastry, or a freshly brewed cup, they may become partners, family, and something deeper than she ever could have dreamed. “Take a break from epic battles and saving the world. Legends & Lattes is a low-stakes fantasy that delivers exactly what's advertised: a wholesome, cozy novel that feels like a warm hug. This is my new comfort read.”—Genevieve Gornichec, author of The Witch's Heart At the Publisher's request, this title is being sold without Digital Rights Management Software (DRM) applied.",
    'industryIdentifiers': [{'type': 'ISBN_13', 'identifier': '9781250886095'},
     {'type': 'ISBN_10', 'identifier': '1250886090'}],
    'readingModes': {'text': True, 'image': False},
    'pageCount': 233,
    'printType': 'BOOK',
    'categories': ['Fiction'],
    'maturityRating': 'NOT_MATURE',
    'allowAnonLogging': True,
    'contentVersion': '2.11.12.0.preview.2',
    'panelizationSummary': {'containsEpubBubbles': False,
     'containsImageBubbles': False},
    'imageLinks': {'smallThumbnail': 'http://books.google.com/books/content?id=7lJzEAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api',
     'thumbnail': 'http://books.google.com/books/content?id=7lJzEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'},
    'language': 'en',
    'previewLink': 'http://books.google.com/books?id=7lJzEAAAQBAJ&printsec=frontcover&dq=intitle:Legends+%26+Lattes+inauthor:Travis+Baldree&hl=&cd=1&source=gbs_api',
    'infoLink': 'https://play.google.com/store/books/details?id=7lJzEAAAQBAJ&source=gbs_api',
    'canonicalVolumeLink': 'https://play.google.com/store/books/details?id=7lJzEAAAQBAJ'},
   'saleInfo': {'country': 'US',
    'saleability': 'FOR_SALE',
    'isEbook': True,
    'listPrice': {'amount': 11.99, 'currencyCode': 'USD'},
    'retailPrice': {'amount': 11.99, 'currencyCode': 'USD'},
    'buyLink': 'https://play.google.com/store/books/details?id=7lJzEAAAQBAJ&rdid=book-7lJzEAAAQBAJ&rdot=1&source=gbs_api',
    'offers': [{'finskyOfferType': 1,
      'listPrice': {'amountInMicros': 11990000, 'currencyCode': 'USD'},
      'retailPrice': {'amountInMicros': 11990000, 'currencyCode': 'USD'},
      'giftable': True}]},
   'accessInfo': {'country': 'US',
    'viewability': 'PARTIAL',
    'embeddable': True,
    'publicDomain': False,
    'textToSpeechPermission': 'ALLOWED',
    'epub': {'isAvailable': True},
    'pdf': {'isAvailable': False},
    'webReaderLink': 'http://play.google.com/books/reader?id=7lJzEAAAQBAJ&hl=&source=gbs_api',
    'accessViewStatus': 'SAMPLE',
    'quoteSharingAllowed': False},
   'searchInfo': {'textSnippet': 'This is my new comfort read.”—Genevieve Gornichec, author of The Witch&#39;s Heart At the Publisher&#39;s request, this title is being sold without Digital Rights Management Software (DRM) applied.'}},
  {'kind': 'books#volume',
   'id': 'OFvJEQAAQBAJ',
   'etag': 'MEXLaSWORzM',
   'selfLink': 'https://www.googleapis.com/books/v1/volumes/OFvJEQAAQBAJ',
   'volumeInfo': {'title': 'Legends & Lattes',
    'subtitle': 'The Graphic Novel',
    'authors': ['Travis Baldree'],
    'publisher': 'Pan Macmillan',
    'publishedDate': '2026-10-08',
    'description': "The stunning graphic novel adaptation of the beloved cosy fantasy sensation Legends & Lattes by Travis Baldree. 'I can smell the coffee and taste the midnight crescents. The modern classic about starting over truly comes to life . . . I wish I could live in every panel' -Matt Dinniman, New York Times bestselling author of Dungeon Crawler Carl High fantasy, low stakes – with a double-shot of coffee. After decades of adventuring, Viv the orc barbarian is finally hanging up her sword for good. Now she sets her sights on a new dream – for she plans to open the first coffee shop in the city of Thune. Even though no one there knows what coffee actually is. If Viv wants to put the past behind her, she can’t go it alone. And help might arrive from unexpected quarters. Yet old rivals and new stand in the way of success. And Thune’s shady underbelly could make it all too easy for Viv to take up the blade once more. But the true reward of the uncharted path is the travellers you meet along the way. Whether bound by ancient magic, delicious pastries or a freshly brewed cup, they may become something deeper than Viv ever could have imagined . . . 'This is a warm hug of a book, a place to retreat from the world for a little while, drink a coffee, and come out a little better' – T. Kingfisher, bestselling author of Nettle & Bone",
    'industryIdentifiers': [{'type': 'ISBN_13', 'identifier': '9781037416989'},
     {'type': 'ISBN_10', 'identifier': '1037416988'}],
    'readingModes': {'text': True, 'image': False},
    'pageCount': 0,
    'printType': 'BOOK',
    'categories': ['Comics & Graphic Novels'],
    'maturityRating': 'NOT_MATURE',
    'allowAnonLogging': False,
    'contentVersion': 'preview-1.0.0',
    'panelizationSummary': {'containsEpubBubbles': False,
     'containsImageBubbles': False},
    'imageLinks': {'smallThumbnail': 'http://books.google.com/books/content?id=OFvJEQAAQBAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api',
     'thumbnail': 'http://books.google.com/books/content?id=OFvJEQAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api'},
    'language': 'en',
    'previewLink': 'http://books.google.com/books?id=OFvJEQAAQBAJ&dq=intitle:Legends+%26+Lattes+inauthor:Travis+Baldree&hl=&cd=2&source=gbs_api',
    'infoLink': 'http://books.google.com/books?id=OFvJEQAAQBAJ&dq=intitle:Legends+%26+Lattes+inauthor:Travis+Baldree&hl=&source=gbs_api',
    'canonicalVolumeLink': 'https://books.google.com/books/about/Legends_Lattes.html?hl=&id=OFvJEQAAQBAJ'},
   'saleInfo': {'country': 'US',
    'saleability': 'NOT_FOR_SALE',
    'isEbook': False},
   'accessInfo': {'country': 'US',
    'viewability': 'NO_PAGES',
    'embeddable': False,
    'publicDomain': False,
    'textToSpeechPermission': 'ALLOWED',
    'epub': {'isAvailable': False},
    'pdf': {'isAvailable': False},
    'webReaderLink': 'http://play.google.com/books/reader?id=OFvJEQAAQBAJ&hl=&source=gbs_api',
    'accessViewStatus': 'NONE',
    'quoteSharingAllowed': False},
   'searchInfo': {'textSnippet': 'The stunning graphic novel adaptation of the beloved cosy fantasy sensation Legends &amp; Lattes by Travis Baldree.'}},
  {'kind': 'books#volume',
   'id': 'kLe0EQAAQBAJ',
   'etag': 'Qi4z41q1BLE',
   'selfLink': 'https://www.googleapis.com/books/v1/volumes/kLe0EQAAQBAJ',
   'volumeInfo': {'title': 'Tales from the Territory',
    'subtitle': 'A Cosy Collection of Legends & Lattes Short Stories',
    'authors': ['Travis Baldree'],
    'publisher': 'Pan Macmillan',
    'publishedDate': '2026-10-01',
    'description': "From Sunday Times bestseller Travis Baldree, Tales from the Territory is a beautiful collection of cosy fantasy tales, set in the much-loved world of Legends & Lattes. There are many tales yet untold . . . In 'GOBLINS & GREATCOATS': Chaos goblin Zyll is involved in a case of mistaken identity, where she solves a murder at an inn whilst simultaneously stealing all the cutlery. In 'JUST A THIMBLEFUL': The sweet rattkin baker Thimble finds a new home for his soon-to-be famous cinnamon rolls. In 'PAGES TO FILL': An act of mercy leads to a life-changing discovery for warrior orc Viv. In 'MIROGRAPH', young succubus Tandri assists a university professor on a mysterious project where art and science collide. In 'CAVALIERS & COFFEES', Viv, now the owner of Legends & Lattes coffee shop, discovers that imitation is not the highest form of flattery. Featuring bespoke, full-page colour illustrations and endpapers, this is a deluxe collection of cosy short stories. Praise for the Legends & Lattes series: 'A warm hug of a book' – T. Kingfisher, Sunday Times bestselling author of Hemlock & Silver 'Funny, unexpected and touching' – Ben Aaronovitch, author of Rivers of London series 'Hilarious, heartwarming, and wholesome as heck' – Nicholas Eames, author of Kings of the Wyld 'Travis is clearly the King of Cosy Fantasy . . . I enjoyed this enormously' – SFF World",
    'industryIdentifiers': [{'type': 'ISBN_13', 'identifier': '9781035083367'},
     {'type': 'ISBN_10', 'identifier': '1035083361'}],
    'readingModes': {'text': True, 'image': False},
    'pageCount': 0,
    'printType': 'BOOK',
    'categories': ['Fiction'],
    'maturityRating': 'NOT_MATURE',
    'allowAnonLogging': False,
    'contentVersion': 'preview-1.0.0',
    'panelizationSummary': {'containsEpubBubbles': False,
     'containsImageBubbles': False},
    'imageLinks': {'smallThumbnail': 'http://books.google.com/books/content?id=kLe0EQAAQBAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api',
     'thumbnail': 'http://books.google.com/books/content?id=kLe0EQAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api'},
    'language': 'en',
    'previewLink': 'http://books.google.com/books?id=kLe0EQAAQBAJ&dq=intitle:Legends+%26+Lattes+inauthor:Travis+Baldree&hl=&cd=3&source=gbs_api',
    'infoLink': 'http://books.google.com/books?id=kLe0EQAAQBAJ&dq=intitle:Legends+%26+Lattes+inauthor:Travis+Baldree&hl=&source=gbs_api',
    'canonicalVolumeLink': 'https://books.google.com/books/about/Tales_from_the_Territory.html?hl=&id=kLe0EQAAQBAJ'},
   'saleInfo': {'country': 'US',
    'saleability': 'NOT_FOR_SALE',
    'isEbook': False},
   'accessInfo': {'country': 'US',
    'viewability': 'NO_PAGES',
    'embeddable': False,
    'publicDomain': False,
    'textToSpeechPermission': 'ALLOWED',
    'epub': {'isAvailable': False},
    'pdf': {'isAvailable': False},
    'webReaderLink': 'http://play.google.com/books/reader?id=kLe0EQAAQBAJ&hl=&source=gbs_api',
    'accessViewStatus': 'NONE',
    'quoteSharingAllowed': False},
   'searchInfo': {'textSnippet': 'Featuring bespoke, full-page colour illustrations and endpapers, this is a deluxe collection of cosy short stories.'}},
  {'kind': 'books#volume',
   'id': 'fO-dEQAAQBAJ',
   'etag': 'bSgLjYCMu8I',
   'selfLink': 'https://www.googleapis.com/books/v1/volumes/fO-dEQAAQBAJ',
   'volumeInfo': {'title': 'Legends & Lattes Deluxe Boxed Set',
    'authors': ['Travis Baldree'],
    'publisher': 'Tor Books',
    'publishedDate': '2026-11-17',
    'description': 'The Legends & Lattes Deluxe Boxed Set contains all three deluxe volumes of the #1 New York Times bestselling cozy fantasy series--Legends & Lattes, Bookshops & Bonedust, and Brigands & Breadknives. The #1 New York Times bestselling Legends & Lattes series, now collected in a beautifully packaged boxed set for the first time! Meet Viv, battle-weary orc seeking a fresh start after a lifetime of bounties and bloodshed, who hangs up her sword and opens the first ever coffee shop in the city of Thune. But old and new rivals stand in the way of success -- not to mention the fact that no one has the faintest idea what coffee actually is. If Viv wants to put the blade behind her and make her plans a reality, she won\'t be able to go it alone. Legends & Lattes, Bookshops & Bonedust, and Brigands & Breadknives are set in a cozy fantasy world where friendship, kindness, and a love of books is more important than battles and bloodshed, and take readers on three enchanting adventures with a fantasy crew like no other. "Hilarious, heartwarming, and wholesome as heck."--Nicholas Eames, author of Kings of the Wyld "Set against an epic world of adventure, Travis Baldree writes about the small victories that make life worthwhile. It is glorious."--Ben Aaronovitch, bestselling author of Rivers of London',
    'industryIdentifiers': [{'type': 'ISBN_13', 'identifier': '9781250453273'},
     {'type': 'ISBN_10', 'identifier': '1250453275'}],
    'readingModes': {'text': True, 'image': False},
    'pageCount': 0,
    'printType': 'BOOK',
    'categories': ['Fiction'],
    'maturityRating': 'NOT_MATURE',
    'allowAnonLogging': False,
    'contentVersion': 'preview-1.0.0',
    'panelizationSummary': {'containsEpubBubbles': False,
     'containsImageBubbles': False},
    'imageLinks': {'smallThumbnail': 'http://books.google.com/books/content?id=fO-dEQAAQBAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api',
     'thumbnail': 'http://books.google.com/books/content?id=fO-dEQAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api'},
    'language': 'en',
    'previewLink': 'http://books.google.com/books?id=fO-dEQAAQBAJ&dq=intitle:Legends+%26+Lattes+inauthor:Travis+Baldree&hl=&cd=4&source=gbs_api',
    'infoLink': 'http://books.google.com/books?id=fO-dEQAAQBAJ&dq=intitle:Legends+%26+Lattes+inauthor:Travis+Baldree&hl=&source=gbs_api',
    'canonicalVolumeLink': 'https://books.google.com/books/about/Legends_Lattes_Deluxe_Boxed_Set.html?hl=&id=fO-dEQAAQBAJ'},
   'saleInfo': {'country': 'US',
    'saleability': 'NOT_FOR_SALE',
    'isEbook': False},
   'accessInfo': {'country': 'US',
    'viewability': 'NO_PAGES',
    'embeddable': False,
    'publicDomain': False,
    'textToSpeechPermission': 'ALLOWED',
    'epub': {'isAvailable': False},
    'pdf': {'isAvailable': False},
    'webReaderLink': 'http://play.google.com/books/reader?id=fO-dEQAAQBAJ&hl=&source=gbs_api',
    'accessViewStatus': 'NONE',
    'quoteSharingAllowed': False},
   'searchInfo': {'textSnippet': '&quot;Hilarious, heartwarming, and wholesome as heck.&quot;--Nicholas Eames, author of Kings of the Wyld &quot;Set against an epic world of adventure, Travis Baldree writes about the small victories that make life worthwhile. It is glorious.'}},
  {'kind': 'books#volume',
   'id': 'fF-w0QEACAAJ',
   'etag': '2pclIaU91z4',
   'selfLink': 'https://www.googleapis.com/books/v1/volumes/fF-w0QEACAAJ',
   'volumeInfo': {'title': 'Legends & Lattes',
    'authors': ['Travis Baldree'],
    'publishedDate': '2025-08-22',
    'description': "Korean edition of [Legends & Lattes] by Travis Baldree. An Instant New York Times Bestseller. A Barnes & Noble Best Book of 2022. A Library Reads Pick. A Goodreads Best Fantasy Choice Award Nominee. The much-beloved BookTok sensation, Travis Baldree's novel of high fantasy and low stakes. Korean edition translated by Ji Hee Han.",
    'industryIdentifiers': [{'type': 'ISBN_13',
      'identifier': '9791170965206'}],
    'readingModes': {'text': False, 'image': False},
    'pageCount': 0,
    'printType': 'BOOK',
    'categories': ['Fiction'],
    'maturityRating': 'NOT_MATURE',
    'allowAnonLogging': False,
    'contentVersion': 'preview-1.0.0',
    'panelizationSummary': {'containsEpubBubbles': False,
     'containsImageBubbles': False},
    'imageLinks': {'smallThumbnail': 'http://books.google.com/books/content?id=fF-w0QEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api',
     'thumbnail': 'http://books.google.com/books/content?id=fF-w0QEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api'},
    'language': 'ko',
    'previewLink': 'http://books.google.com/books?id=fF-w0QEACAAJ&dq=intitle:Legends+%26+Lattes+inauthor:Travis+Baldree&hl=&cd=5&source=gbs_api',
    'infoLink': 'http://books.google.com/books?id=fF-w0QEACAAJ&dq=intitle:Legends+%26+Lattes+inauthor:Travis+Baldree&hl=&source=gbs_api',
    'canonicalVolumeLink': 'https://books.google.com/books/about/Legends_Lattes.html?hl=&id=fF-w0QEACAAJ'},
   'saleInfo': {'country': 'US',
    'saleability': 'NOT_FOR_SALE',
    'isEbook': False},
   'accessInfo': {'country': 'US',
    'viewability': 'NO_PAGES',
    'embeddable': False,
    'publicDomain': False,
    'textToSpeechPermission': 'ALLOWED',
    'epub': {'isAvailable': False},
    'pdf': {'isAvailable': False},
    'webReaderLink': 'http://play.google.com/books/reader?id=fF-w0QEACAAJ&hl=&source=gbs_api',
    'accessViewStatus': 'NONE',
    'quoteSharingAllowed': False},
   'searchInfo': {'textSnippet': 'Korean edition of [Legends &amp; Lattes] by Travis Baldree.'}},
  {'kind': 'books#volume',
   'id': '9uF0EAAAQBAJ',
   'etag': 'oMQESeNGWwI',
   'selfLink': 'https://www.googleapis.com/books/v1/volumes/9uF0EAAAQBAJ',
   'volumeInfo': {'title': 'Legends & Lattes',
    'subtitle': 'A heart-warming cosy fantasy and TikTok sensation',
    'authors': ['Travis Baldree'],
    'publisher': 'Pan Macmillan',
    'publishedDate': '2022-06-16',
    'description': "THE INSTANT NEW YORK TIMES BESTSELLER AND TIK TOK SENSATION A cosy, heartwarming slice-of-life fantasy about found families and fresh starts. 'This is a warm hug of a book' – T. Kingfisher, bestselling author of Nettle & Bone High fantasy, low stakes – with a double-shot of coffee. After decades of adventuring, Viv the orc barbarian is finally hanging up her sword for good. Now she sets her sights on a new dream – for she plans to open the first coffee shop in the city of Thune. Even though no one there knows what coffee actually is. If Viv wants to put the past behind her, she can’t go it alone. And help might arrive from unexpected quarters. Yet old rivals and new stand in the way of success. And Thune’s shady underbelly could make it all too easy for Viv to take up the blade once more. But the true reward of the uncharted path is the travellers you meet along the way. Whether bound by ancient magic, delicious pastries or a freshly brewed cup, they may become something deeper than Viv ever could have imagined . . . ‘The most fun I've ever had in a coffee shop’ – Ben Aaronovitch, bestselling author of Rivers of London 'This sapphic triumph is an absolute must' - Rebecca Thorne, bestselling author of Can't Spell Treason Without Tea Return to the world of Legends & Lattes with Bookshops & Bonedust, the hilarious and heartwarming prequel.",
    'industryIdentifiers': [{'type': 'ISBN_13', 'identifier': '9781035007332'},
     {'type': 'ISBN_10', 'identifier': '1035007339'}],
    'readingModes': {'text': True, 'image': False},
    'pageCount': 309,
    'printType': 'BOOK',
    'categories': ['Fiction'],
    'maturityRating': 'MATURE',
    'allowAnonLogging': True,
    'contentVersion': '1.8.9.0.preview.2',
    'panelizationSummary': {'containsEpubBubbles': False,
     'containsImageBubbles': False},
    'imageLinks': {'smallThumbnail': 'http://books.google.com/books/content?id=9uF0EAAAQBAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api',
     'thumbnail': 'http://books.google.com/books/content?id=9uF0EAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api'},
    'language': 'en',
    'previewLink': 'http://books.google.com/books?id=9uF0EAAAQBAJ&dq=intitle:Legends+%26+Lattes+inauthor:Travis+Baldree&hl=&cd=6&source=gbs_api',
    'infoLink': 'http://books.google.com/books?id=9uF0EAAAQBAJ&dq=intitle:Legends+%26+Lattes+inauthor:Travis+Baldree&hl=&source=gbs_api',
    'canonicalVolumeLink': 'https://books.google.com/books/about/Legends_Lattes.html?hl=&id=9uF0EAAAQBAJ'},

In [7]:
# better info on the book out of the dictionary 

first_match = result["items"][0]
info = first_match["volumeInfo"]
print(info.get("title"))
print(info.get("authors"))
print(info.get("publisher"))
print(info.get("publishedDate"))
print(info.get("description"))
print(info.get("imageLinks", {}).get("thumbnail"))

Legends & Lattes
['Travis Baldree']
Tor Books
2022-06-07
An Instant New York Times Bestseller A Barnes & Noble Best Book of 2022 A Library Reads Pick An Indie Next Pick A Goodreads Best Fantasy Choice Award Nominee The much-beloved BookTok sensation, Travis Baldree's novel of high fantasy and low stakes. *This new edition includes a very special, never-before-seen bonus story, 'Pages to Fill.'* After a lifetime of bounties and bloodshed, Viv is hanging up her sword for the last time. The battle-weary orc aims to start fresh, opening the first ever coffee shop in the city of Thune. But old and new rivals stand in the way of success — not to mention the fact that no one has the faintest idea what coffee actually is. If Viv wants to put the blade behind her and make her plans a reality, she won't be able to go it alone. But the true rewards of the uncharted path are the travelers you meet along the way. And whether drawn together by ancient magic, flaky pastry, or a freshly brewed cup, they may become partners, family, and something deeper than she ever could have dreamed. “Take a break from epic battles and saving the world. Legends & Lattes is a low-stakes fantasy that delivers exactly what's advertised: a wholesome, cozy novel that feels like a warm hug. This is my new comfort read.”—Genevieve Gornichec, author of The Witch's Heart At the Publisher's request, this title is being sold without Digital Rights Management Software (DRM) applied.
http://books.google.com/books/content?id=7lJzEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api

In [8]:
#Review Open Library instead
def search_open_library(title, author):
    url = "https://openlibrary.org/search.json"
    params = {"title": title, "author": author}
    response = requests.get(url, params=params)
    return response.json()

ol_result = search_open_library("Legends & Lattes", "Travis Baldree")
ol_result["docs"][0] if ol_result["docs"] else "No match"

{'author_key': ['OL9109447A'],
 'author_name': ['Travis Baldree'],
 'cover_edition_key': 'OL38237074M',
 'cover_i': 13028635,
 'ebook_access': 'no_ebook',
 'edition_count': 19,
 'first_publish_year': 2022,
 'has_fulltext': False,
 'key': '/works/OL27591348W',
 'language': ['dut', 'spa', 'eng', 'ger'],
 'public_scan_b': False,
 'title': 'Legends & Lattes'}

## Load in manual cozy fantasy spreadsheet I created and add info with Google API

In [9]:
#load in csv

titles_df = pd.read_csv("../raw/raw_title_list.csv")
titles_df.head()

,title,author,approx_year,found_on_list,self_pub
0,Legends & Lattes,Travis Baldree,2022,Goodreads,True
1,The House in the Cerulean Sea,T.J. Klune,2020,Goodreads,False
2,The Spellshop,Sarah Beth Durst,2024,Goodreads,False
3,Emily Wilde's Encyclopaedia of Faeries,Heather Fawcett\r,2023,Goodreads,False
4,A Wizard’s Guide to Defensive Baking,T. Kingfisher,2020,Goodreads,False

In [11]:
#grabbing extra info and writing to a new clean csv
results = []

for idx, row in titles_df.iterrows():
    print(f"Processing {idx+1}/{len(titles_df)}: {row['title']}")
    try:
        data = search_google_books(row["title"], row["author"])
        ...
        if data.get("totalItems", 0) > 0:
            info = data["items"][0]["volumeInfo"]
            results.append({
                "title": row["title"],
                "author": row["author"],
                "publisher_raw": info.get("publisher"),
                "published_date": info.get("publishedDate"),
                "page_count": info.get("pageCount"),
                "description": info.get("description"),
                "cover_url": info.get("imageLinks", {}).get("thumbnail"),
                "found_on_list": row["found_on_list"],
            })
        else:
            results.append({"title": row["title"], "author": row["author"], "publisher_raw": None})
    except Exception as e:
        print(f"Failed on {row['title']}: {e}")
        results.append({"title": row["title"], "author": row["author"], "publisher_raw": None})

    time.sleep(1)  

metadata_df = pd.DataFrame(results)
metadata_df.to_csv("../raw/google_books_metadata.csv", index=False)

Processing 1/99: Legends & Lattes
Processing 2/99: The House in the Cerulean Sea
Processing 3/99: The Spellshop
Processing 4/99: Emily Wilde's Encyclopaedia of Faeries
Processing 5/99: A Wizard’s Guide to Defensive Baking
Processing 6/99: The Very Secret Society of Irregular Witches
Processing 7/99: A Psalm for the Wild-Built
Processing 8/99: Bookshops & Bonedust
Processing 9/99: Can't Spell Treason Without Tea
Processing 10/99: Tress of the Emerald Sea
Processing 11/99: The Teller of Small Fortunes
Processing 12/99: Brigands & Breadknives
Processing 13/99: A Witch's Guide to Magical Innkeeping
Processing 14/99: Emily Wilde's Compendium of Lost Tales
Processing 15/99: Nettle & Bone
Processing 16/99: Half a Soul
Processing 17/99: Agnes Aubert's Mystical Cat Shelter
Processing 18/99: A Coup of Tea
Processing 19/99: The House Witch
Processing 20/99: Howl's Moving Castle
Processing 21/99: A Fellowship of Bakers & Magic
Processing 22/99: That Time I Got Drunk and Saved a Demon
Processing 23/99: The Tea Dragon Society
Processing 24/99: Under the Whispering Door
Processing 25/99: The Honey Witch
Processing 26/99: Cursed Cocktails
Processing 27/99: Swordheart
Processing 28/99: Violet Thistlewaite Is Not a Villain Anymore
Processing 29/99: Rewitched
Processing 30/99: A Pirate's Life for Tea
Processing 31/99: The Faraway Inn
Processing 32/99: Keeper of Enchanted Rooms
Processing 33/99: Somewhere Beyond the Sea
Processing 34/99: The Undertaking of Hart and Mercy
Processing 35/99: Paladin's Grace
Processing 36/99: In the Company of Witches
Processing 37/99: Flowerheart
Processing 38/99: The Keeper of Magical Things
Processing 39/99: The Phoenix Keeper
Processing 40/99: The Baby Dragon Café
Processing 41/99: The Bookshop and the Barbarian
Processing 42/99: Miss Percy's Pocket Guide to the Care and Feeding of British Dragons
Processing 43/99: Stay for a Spell
Processing 44/99: Forged by Magic
Processing 45/99: Water Moon
Processing 46/99: The Cybernetic Tea Shop
Processing 47/99: The Long Way to a Small, Angry Planet
Processing 48/99: Mindtouch
Processing 49/99: Quarter Share
Processing 50/99: Scales and Sensibility
Processing 51/99: Coffee, Milk & Spider Silk
Processing 52/99: The Wizard's Butler
Processing 53/99: Axtara - Banking and Finance
Processing 54/99: The Hands of the Emperor
Processing 55/99: House of Many Ways
Processing 56/99: Vanessa Yu's Magical Paris Tea Shop
Processing 57/99: Baking Bad
Processing 58/99: Stargazy Pie
Processing 59/99: Magician's Hoard
Processing 60/99: Mr. Penumbra's 24-Hour Bookstore
Processing 61/99: The Herbwitch's Apprentice
Processing 62/99: Payback's a Witch
Processing 63/99: The Witching Flour
Processing 64/99: Slouch Witch
Processing 65/99: Dealing with Dragons
Processing 66/99: Fanuilh
Processing 67/99: The Dragon with a Chocolate Heart
Processing 68/99: Old Flames and New Fortunes
Processing 69/99: The Full Moon Coffee Shop
Processing 70/99: Calculated Whisk
Processing 71/99: Drop of a Hat
Processing 72/99: Tempests & Tea Leaves
Processing 73/99: The Witch at the Edge of the Wood
Processing 74/99: Managing the Vampire's Mansion
Processing 75/99: Fates & Family: A Cozy Slice-of-Life Fantasy
Processing 76/99: A Spot of Tea and Sorcery - Volume 1
Processing 77/99: A Dragon Rider's Guide to Retirement
Processing 78/99: The Remarkable Retirement of Edna Fisher
Processing 79/99: The Lord of Stariel
Processing 80/99: Between
Processing 81/99: A Prayer for the Crown-Shy
Processing 82/99: Small Miracles
Processing 83/99: The Book of Zog
Processing 84/99: The Girl Who Kept the Castle
Processing 85/99: The Ogress and the Orphans
Processing 86/99: I'm Afraid You've Got Dragons
Processing 87/99: The Fairy Bargains of Prospect Hill
Processing 88/99: Stardust
Processing 89/99: Ten Thousand Stitches
Processing 90/99: The Goblin Emperor
Processing 91/99: The Wisteria Society of Lady Scoundrels
Processing 92/99: Chocolates and Claws
Processing 93/99: The Little Shop of Grand Curiosities
Processing 94/99: Winterfrost Market
Processing 95/99: A Rival Most Vial: Potioneering for Love and Profit
Processing 96/99: Beware of Chicken
Processing 97/99: Something Close to Magic
Processing 98/99: The Book Witch
Processing 99/99: Tea & Alchemy

In [12]:
metadata_df[metadata_df["publisher_raw"].isna()]

,title,author,publisher_raw,published_date,page_count,description,cover_url,found_on_list
4,A Wizard’s Guide to Defensive Baking,T. Kingfisher,NaN,2020-07-21,NaN,Fourteen-year-old Mona isn't like the wizards ...,http://books.google.com/books/content?id=ZiWbz...,Goodreads
5,The Very Secret Society of Irregular Witches,Sangu Mandanna\r\n,NaN,NaN,NaN,NaN,NaN,NaN
15,Half a Soul,Olivia Atwater\r,NaN,NaN,NaN,NaN,NaN,NaN
17,A Coup of Tea,Casey Blair,NaN,2022,0.0,"""When the fourth princess of Istalam is due to...",NaN,Reddit
21,That Time I Got Drunk and Saved a Demon,Kimberly Lemming,NaN,NaN,NaN,NaN,NaN,NaN
22,The Tea Dragon Society,K. O'Neill,NaN,NaN,NaN,NaN,NaN,NaN
25,Cursed Cocktails,S.L. Rowland,NaN,NaN,NaN,NaN,NaN,NaN
27,Violet Thistlewaite Is Not a Villain Anymore,Emily Krempholtz\r,NaN,NaN,NaN,NaN,NaN,NaN
29,A Pirate's Life for Tea,Rebecca Thorne,NaN,2023-02-20,0.0,"While hunting for missing dragon eggs, Kianthe...",http://books.google.com/books/content?id=VOScz...,Goodreads
31,Keeper of Enchanted Rooms,Charlie N. Holmberg,NaN,NaN,NaN,NaN,NaN,NaN
33,The Undertaking of Hart and Mercy,Megan Bannen,NaN,NaN,NaN,NaN,NaN,NaN
37,The Keeper of Magical Things,Julie Leong,NaN,NaN,NaN,NaN,NaN,NaN
38,The Phoenix Keeper,S.A. MacLean,NaN,NaN,NaN,NaN,NaN,NaN
39,The Baby Dragon Café,Aamna Qureshi,NaN,NaN,NaN,NaN,NaN,NaN
40,The Bookshop and the Barbarian,Morgan Stang,NaN,2023,0.0,NaN,NaN,Goodreads
42,Stay for a Spell,Amy Coombe,NaN,NaN,NaN,NaN,NaN,NaN
43,Forged by Magic,Jenna Wolfhart\r,NaN,2023-07-11,0.0,"A heartwarming, feel-good fantasy romance...wi...",http://books.google.com/books/content?id=4xkD0...,Goodreads
45,The Cybernetic Tea Shop,Meredith Katz,NaN,2016,NaN,Clara Gutierrez is a highly-skilled technician...,NaN,Reddit
46,"The Long Way to a Small, Angry Planet",Becky Chambers\r\n,NaN,NaN,NaN,NaN,NaN,NaN
47,Mindtouch,M.C.A. Hogarth,NaN,NaN,NaN,NaN,NaN,NaN
50,"Coffee, Milk & Spider Silk",Coyote J.M. Edwards,NaN,2021-11-12,0.0,What should a battle-worn 11-foot tall drider ...,http://books.google.com/books/content?id=bo3b0...,Reddit
51,The Wizard's Butler,Nathan Lowell,NaN,2020-10-14,NaN,How an ex-Army medic became butler to a dement...,http://books.google.com/books/content?id=jK8Fz...,Reddit
54,House of Many Ways,Diana Wynne Jones,NaN,NaN,NaN,NaN,NaN,NaN
55,Vanessa Yu's Magical Paris Tea Shop,Roselle Lim,NaN,NaN,NaN,NaN,NaN,NaN
58,Magician's Hoard,Celia Lake,NaN,2023-05-29,0.0,Pross has a simple research question.A widow r...,http://books.google.com/books/content?id=XBgC0...,Reddit
59,Mr. Penumbra's 24-Hour Bookstore,Robin Sloan,NaN,NaN,NaN,NaN,NaN,NaN
60,The Herbwitch's Apprentice,Ireen Chau,NaN,2023-10-17,0.0,"In the kingdom of Olderea, dabbling in witchcr...",http://books.google.com/books/content?id=NXs80...,Reddit
61,Payback's a Witch,Lana Harper,NaN,NaN,NaN,NaN,NaN,NaN
62,The Witching Flour,Samantha Silver,NaN,2021-02-13,268.0,"Welcome to Spellford Cove, where the baking is...",http://books.google.com/books/content?id=W609z...,Reddit
65,Fanuilh,Daniel Hood,NaN,1994,680.0,NaN,NaN,Reddit
69,Calculated Whisk,Lindsay Buroker,NaN,NaN,NaN,NaN,NaN,NaN
70,Drop of a Hat,Sara Bourgeois,NaN,NaN,NaN,NaN,NaN,NaN
71,Tempests & Tea Leaves,Rachel Morgan,NaN,2025-04-17,0.0,Bridgerton meets cozy fae fantasy with a dash ...,http://books.google.com/books/content?id=zfVd0...,Amazon
73,Managing the Vampire's Mansion,K.M. Shea,NaN,2020-04-17,NaN,Ever had ex-housemates you can't get rid of?Wh...,NaN,Amazon
74,Fates & Family: A Cozy Slice-of-Life Fantasy,Toni Binns,NaN,NaN,NaN,NaN,NaN,NaN
75,A Spot of Tea and Sorcery - Volume 1,Sylvia Mercedes,NaN,NaN,NaN,NaN,NaN,NaN
76,A Dragon Rider's Guide to Retirement,Julia Huni,NaN,NaN,NaN,NaN,NaN,NaN
77,The Remarkable Retirement of Edna Fisher,E.M. Anderson,NaN,NaN,NaN,NaN,NaN,NaN
79,Between,L.L. Starling\r,NaN,2020-10-31,NaN,A kindergarten teacher trapped in a fairytale....,http://books.google.com/books/content?id=B3jbz...,Goodreads
80,A Prayer for the Crown-Shy,Becky Chambers,NaN,NaN,NaN,NaN,NaN,NaN
81,Small Miracles,Olivia Atwater\r,NaN,NaN,NaN,NaN,NaN,NaN
82,The Book of Zog,Alec Hutson,NaN,2022-09-12,0.0,What were the Great Old Ones like before they ...,http://books.google.com/books/content?id=TKZfz...,Youtube
86,The Fairy Bargains of Prospect Hill,Rowenna Miller,NaN,NaN,NaN,NaN,NaN,NaN
91,Chocolates and Claws,Claire Mavis,NaN,NaN,NaN,NaN,NaN,NaN
92,The Little Shop of Grand Curiosities,Iris Lake,NaN,NaN,NaN,NaN,NaN,NaN
93,Winterfrost Market,Jenny Sandiford,NaN,2024-10-24,0.0,A tea-loving mortal with a warm heart. A world...,http://books.google.com/books/content?id=oenv0...,Goodreads
94,A Rival Most Vial: Potioneering for Love and P...,R.K. Ashwick,NaN,NaN,NaN,NaN,NaN,NaN
95,Beware of Chicken,CasualFarmer,NaN,NaN,NaN,NaN,NaN,NaN
96,Something Close to Magic,Emma Mills,NaN,NaN,NaN,NaN,NaN,NaN
97,The Book Witch,Meg Shaffer\r,NaN,NaN,NaN,NaN,NaN,NaN
98,Tea & Alchemy,Sharon Lynn Fisher,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
import re

def clean_text(text):
    if pd.isna(text):
        return text
    cleaned = re.sub(r'[\r\n]+', ' ', text)   # replace any carriage returns/newlines with a space
    cleaned = re.sub(r'\s+', ' ', cleaned).strip()  # collapse leftover double-spaces, trim ends
    return cleaned

titles_df["title"] = titles_df["title"].apply(clean_text)
titles_df["author"] = titles_df["author"].apply(clean_text)

In [14]:
missing_mask = metadata_df["publisher_raw"].isna()
missing_df = metadata_df[missing_mask].copy()
print(f"{len(missing_df)} titles missing data — retrying with cleaned text")

# pull the now-cleaned title/author back in for these same rows
missing_df["title"] = titles_df.loc[missing_df.index, "title"]
missing_df["author"] = titles_df.loc[missing_df.index, "author"]

for idx, row in missing_df.iterrows():
    print(f"Retrying: {row['title']}")
    data = search_google_books(row["title"], row["author"])
    if data.get("totalItems", 0) > 0:
        info = data["items"][0]["volumeInfo"]
        metadata_df.loc[idx, "publisher_raw"] = info.get("publisher")
        metadata_df.loc[idx, "published_date"] = info.get("publishedDate")
        metadata_df.loc[idx, "page_count"] = info.get("pageCount")
        metadata_df.loc[idx, "description"] = info.get("description")
        metadata_df.loc[idx, "cover_url"] = info.get("imageLinks", {}).get("thumbnail")
    time.sleep(1)

51 titles missing data — retrying with cleaned text
Retrying: A Wizard’s Guide to Defensive Baking
Retrying: The Very Secret Society of Irregular Witches
Retrying: Half a Soul
Retrying: A Coup of Tea
Retrying: That Time I Got Drunk and Saved a Demon
Retrying: The Tea Dragon Society
Retrying: Cursed Cocktails
Retrying: Violet Thistlewaite Is Not a Villain Anymore
Retrying: A Pirate's Life for Tea
Retrying: Keeper of Enchanted Rooms
Retrying: The Undertaking of Hart and Mercy
Retrying: The Keeper of Magical Things
Retrying: The Phoenix Keeper
Retrying: The Baby Dragon Café
Retrying: The Bookshop and the Barbarian
Retrying: Stay for a Spell
Retrying: Forged by Magic
Retrying: The Cybernetic Tea Shop
Retrying: The Long Way to a Small, Angry Planet
Retrying: Mindtouch
Retrying: Coffee, Milk & Spider Silk
Retrying: The Wizard's Butler
Retrying: House of Many Ways
Retrying: Vanessa Yu's Magical Paris Tea Shop
Retrying: Magician's Hoard
Retrying: Mr. Penumbra's 24-Hour Bookstore
Retrying: The Herbwitch's Apprentice
Retrying: Payback's a Witch
Retrying: The Witching Flour
Retrying: Fanuilh
Retrying: Calculated Whisk
Retrying: Drop of a Hat
Retrying: Tempests & Tea Leaves
Retrying: Managing the Vampire's Mansion
Retrying: Fates & Family: A Cozy Slice-of-Life Fantasy
Retrying: A Spot of Tea and Sorcery - Volume 1
Retrying: A Dragon Rider's Guide to Retirement
Retrying: The Remarkable Retirement of Edna Fisher
Retrying: Between
Retrying: A Prayer for the Crown-Shy
Retrying: Small Miracles
Retrying: The Book of Zog
Retrying: The Fairy Bargains of Prospect Hill
Retrying: Chocolates and Claws
Retrying: The Little Shop of Grand Curiosities
Retrying: Winterfrost Market
Retrying: A Rival Most Vial: Potioneering for Love and Profit
Retrying: Beware of Chicken
Retrying: Something Close to Magic
Retrying: The Book Witch
Retrying: Tea & Alchemy

In [16]:
def search_open_library(title, author, timeout=10):
    url = "https://openlibrary.org/search.json"
    params = {"title": title, "author": author}
    response = requests.get(url, params=params, timeout=timeout)
    return response.json()

still_missing_mask = metadata_df["publisher_raw"].isna()
still_missing_df = metadata_df[still_missing_mask].copy()
print(f"{len(still_missing_df)} titles heading to Open Library")

for idx, row in still_missing_df.iterrows():
    print(f"Open Library lookup: {row['title']}")
    try:
        data = search_open_library(row["title"], row["author"])
        if data.get("numFound", 0) > 0:
            doc = data["docs"][0]
            publishers = doc.get("publisher")
            metadata_df.loc[idx, "publisher_raw"] = publishers[0] if publishers else None

            year = doc.get("first_publish_year")
            metadata_df.loc[idx, "published_date"] = str(year) if year is not None else None

            metadata_df.loc[idx, "page_count"] = doc.get("number_of_pages_median")
            cover_id = doc.get("cover_i")
            metadata_df.loc[idx, "cover_url"] = f"https://covers.openlibrary.org/b/id/{cover_id}-M.jpg" if cover_id else None
            metadata_df.loc[idx, "source"] = "open_library"
    except Exception as e:
        print(f"Failed on {row['title']}: {e}")
    time.sleep(1)

37 titles heading to Open Library
Open Library lookup: A Wizard’s Guide to Defensive Baking
Open Library lookup: A Coup of Tea
Open Library lookup: That Time I Got Drunk and Saved a Demon
Open Library lookup: Violet Thistlewaite Is Not a Villain Anymore
Open Library lookup: A Pirate's Life for Tea
Open Library lookup: The Undertaking of Hart and Mercy
Open Library lookup: The Keeper of Magical Things
Open Library lookup: The Baby Dragon Café
Open Library lookup: The Bookshop and the Barbarian
Open Library lookup: Forged by Magic
Open Library lookup: The Cybernetic Tea Shop
Open Library lookup: Mindtouch
Open Library lookup: The Wizard's Butler
Open Library lookup: House of Many Ways
Open Library lookup: Magician's Hoard
Open Library lookup: Mr. Penumbra's 24-Hour Bookstore
Open Library lookup: The Herbwitch's Apprentice
Open Library lookup: The Witching Flour
Open Library lookup: Fanuilh
Open Library lookup: Calculated Whisk
Open Library lookup: Drop of a Hat
Open Library lookup: Tempests & Tea Leaves
Open Library lookup: Managing the Vampire's Mansion
Open Library lookup: Fates & Family: A Cozy Slice-of-Life Fantasy
Open Library lookup: A Spot of Tea and Sorcery - Volume 1
Open Library lookup: A Dragon Rider's Guide to Retirement
Open Library lookup: The Remarkable Retirement of Edna Fisher
Open Library lookup: Between
Open Library lookup: A Prayer for the Crown-Shy
Open Library lookup: Small Miracles
Open Library lookup: The Book of Zog
Open Library lookup: The Fairy Bargains of Prospect Hill
Open Library lookup: Chocolates and Claws
Open Library lookup: The Little Shop of Grand Curiosities
Open Library lookup: Winterfrost Market
Open Library lookup: A Rival Most Vial: Potioneering for Love and Profit
Open Library lookup: Beware of Chicken

In [18]:
metadata_df.to_csv("../raw/google_books_metadata.csv", index=False)
truly_missing = metadata_df[metadata_df["publisher_raw"].isna()]
print(f"{len(truly_missing)} titles not found in either source")
truly_missing[["title", "author"]]

37 titles not found in either source

                                                title              author
4                A Wizard’s Guide to Defensive Baking       T. Kingfisher
17                                      A Coup of Tea         Casey Blair
21            That Time I Got Drunk and Saved a Demon    Kimberly Lemming
27       Violet Thistlewaite Is Not a Villain Anymore  Emily Krempholtz\r
29                            A Pirate's Life for Tea      Rebecca Thorne
33                  The Undertaking of Hart and Mercy        Megan Bannen
37                       The Keeper of Magical Things         Julie Leong
39                               The Baby Dragon Café       Aamna Qureshi
40                     The Bookshop and the Barbarian        Morgan Stang
43                                    Forged by Magic    Jenna Wolfhart\r
45                            The Cybernetic Tea Shop       Meredith Katz
47                                          Mindtouch      M.C.A. Hogarth
51                                The Wizard's Butler       Nathan Lowell
54                                 House of Many Ways   Diana Wynne Jones
58                                   Magician's Hoard          Celia Lake
59                   Mr. Penumbra's 24-Hour Bookstore         Robin Sloan
60                         The Herbwitch's Apprentice          Ireen Chau
62                                 The Witching Flour     Samantha Silver
65                                            Fanuilh         Daniel Hood
69                                   Calculated Whisk     Lindsay Buroker
70                                      Drop of a Hat      Sara Bourgeois
71                              Tempests & Tea Leaves       Rachel Morgan
73                     Managing the Vampire's Mansion           K.M. Shea
74       Fates & Family: A Cozy Slice-of-Life Fantasy          Toni Binns
75               A Spot of Tea and Sorcery - Volume 1     Sylvia Mercedes
76               A Dragon Rider's Guide to Retirement          Julia Huni
77           The Remarkable Retirement of Edna Fisher       E.M. Anderson
79                                            Between     L.L. Starling\r
80                         A Prayer for the Crown-Shy      Becky Chambers
81                                     Small Miracles    Olivia Atwater\r
82                                    The Book of Zog         Alec Hutson
86                The Fairy Bargains of Prospect Hill      Rowenna Miller
91                               Chocolates and Claws        Claire Mavis
92               The Little Shop of Grand Curiosities           Iris Lake
93                                 Winterfrost Market     Jenny Sandiford
94  A Rival Most Vial: Potioneering for Love and P...        R.K. Ashwick
95                                  Beware of Chicken        CasualFarmer

In [19]:
metadata_df = metadata_df.drop_duplicates(subset=["title", "author"])
metadata_df["published_date"] = pd.to_datetime(metadata_df["published_date"], errors="coerce")
metadata_df["pub_year"] = metadata_df["published_date"].dt.year

In [20]:
traditional_imprints = [
    "tor", "bramble", "ace", "orbit", "del rey", "podium",
    "harpervoyager", "angry robot", "daw", "gollancz", "saga press"
]

def classify_publisher(publisher_raw):
    if pd.isna(publisher_raw):
        return "unknown"
    p = publisher_raw.lower()
    if "independently published" in p:
        return "self-published"
    for imprint in traditional_imprints:
        if imprint in p:
            return "traditional"
    return "likely self-published"  # catches small/unrecognized presses too — flag for spot-check

metadata_df["pub_category"] = metadata_df["publisher_raw"].apply(classify_publisher)
metadata_df["pub_category"].value_counts()

pub_category
likely self-published    42
unknown                  37
traditional              19
self-published            1
Name: count, dtype: int64

In [21]:
metadata_df[metadata_df["pub_category"] == "likely self-published"][["title", "author", "publisher_raw"]]

,title,author,publisher_raw
3,Emily Wilde's Encyclopaedia of Faeries,Heather Fawcett\r,Random House
5,The Very Secret Society of Irregular Witches,Sangu Mandanna\r\n,Penguin
10,The Teller of Small Fortunes,Julie Leong,Penguin
12,A Witch's Guide to Magical Innkeeping,Sangu Mandanna\n,Penguin
19,Howl's Moving Castle,Diana Wynne Jones,HarperCollins Children's Books
20,A Fellowship of Bakers & Magic,J. Penner,Poisoned Pen Press
22,The Tea Dragon Society,K. O'Neill,Random House
24,The Honey Witch,Sydney J. Shields\r,Redhook
25,Cursed Cocktails,S.L. Rowland,Tales of Aedrea
28,Rewitched,Lucy Jane Wood,Penguin
30,The Faraway Inn,Sarah Beth Durst\r,Random House
31,Keeper of Enchanted Rooms,Charlie N. Holmberg,47North
34,Paladin's Grace,T. Kingfisher,Hachette UK
35,In the Company of Witches,Auralee Wallace,Penguin
36,Flowerheart,Catherine Bakewell,HarperCollins
41,Miss Percy's Pocket Guide to the Care and Feed...,Quenby Olson,World Tree Publishing
42,Stay for a Spell,Amy Coombe,Penguin
44,Water Moon,Samantha Sotto Yambao,Random House
46,"The Long Way to a Small, Angry Planet",Becky Chambers\r\n,Hodderscape
48,Quarter Share,Nathan Lowell,Ridan Publishing
49,Scales and Sensibility,Stephanie Burgis\r\n,Regency Dragons
50,"Coffee, Milk & Spider Silk",Coyote J.M. Edwards,Coyote JM Edwards
53,The Hands of the Emperor,Victoria Goddard,Underhill Books
55,Vanessa Yu's Magical Paris Tea Shop,Roselle Lim,Penguin
56,Baking Bad,Kim M. Watt,Kim Watt
57,Stargazy Pie,Victoria Goddard,Underhill Books
61,Payback's a Witch,Lana Harper,Penguin
63,Slouch Witch,Helen Harper,Harperfire
64,Dealing with Dragons,Patricia C. Wrede\r,Houghton Mifflin Harcourt
66,The Dragon with a Chocolate Heart,Stephanie Burgis\r,Bloomsbury Publishing
67,Old Flames and New Fortunes,Sarah Hogle,Penguin
68,The Full Moon Coffee Shop,Mai Mochizuki,Ballantine Books
72,The Witch at the Edge of the Wood,Liz Delton,Tourmaline & Quartz Publishing LLC
83,The Girl Who Kept the Castle,Ryan Graudin,HarperCollins
84,The Ogress and the Orphans,Kelly Barnhill,"Little, Brown Books for Young Readers"
85,I'm Afraid You've Got Dragons,Peter S. Beagle,Simon and Schuster
87,Stardust,Neil Gaiman,Headline
89,The Goblin Emperor,Katherine Addison,Macmillan
90,The Wisteria Society of Lady Scoundrels,India Holton,Penguin
96,Something Close to Magic,Emma Mills,Simon and Schuster
97,The Book Witch,Meg Shaffer\r,Random House
98,Tea & Alchemy,Sharon Lynn Fisher,47North

In [22]:
uncertain = metadata_df[metadata_df["pub_category"] == "likely self-published"]
publisher_counts = uncertain["publisher_raw"].value_counts()
publisher_counts

publisher_raw
Penguin                                  10
Random House                              5
47North                                   2
HarperCollins                             2
Underhill Books                           2
Simon and Schuster                        2
HarperCollins Children's Books            1
Poisoned Pen Press                        1
Redhook                                   1
Tales of Aedrea                           1
Hachette UK                               1
World Tree Publishing                     1
Hodderscape                               1
Ridan Publishing                          1
Regency Dragons                           1
Coyote JM Edwards                         1
Kim Watt                                  1
Harperfire                                1
Houghton Mifflin Harcourt                 1
Bloomsbury Publishing                     1
Ballantine Books                          1
Tourmaline & Quartz Publishing LLC        1
Little, Brown Books for Young Readers     1
Headline                                  1
Macmillan                                 1
Name: count, dtype: int64

In [24]:
manual_corrections = {
    "Penguin": "traditional",
    "Random House": "traditional",
    "47North": "traditional",  
    "HarperCollins": "traditional",
    "Simon and Schuster": "traditional",
    "HarperCollins Children's Books": "traditional",
    "Poisoned Pen Press": "traditional",
    "Redhook": "traditional",
    "Hachette UK": "traditional",
    "Hodderscape": "traditional",
    "Houghton Mifflin Harcourt": "traditional",
    "Bloomsbury Publishing": "traditional",
    "Ballantine Books": "traditional",
    "Little, Brown Books for Young Readers": "traditional",
    "Headline": "traditional",
    "Macmillan": "traditional",
    "Ridan Publishing": "traditional",

    # Personal/author-run imprints — functionally self-published
    "Tales of Aedrea": "self-published",
    "Regency Dragons": "self-published",
    "Coyote JM Edwards": "self-published",
    "Kim Watt": "self-published",
    "Harperfire": "self-published",
    "Tourmaline & Quartz Publishing LLC": "self-published",
    "Underhill Books": "self-published",
    "World Tree Publishing": "self-published"
}

def apply_manual_override(row):
    if row["publisher_raw"] in manual_corrections:
        return manual_corrections[row["publisher_raw"]]
    return row["pub_category"]

metadata_df["pub_category"] = metadata_df.apply(apply_manual_override, axis=1)
metadata_df["pub_category"].value_counts()

pub_category
traditional       52
unknown           37
self-published    10
Name: count, dtype: int64

In [27]:
truly_missing = metadata_df[metadata_df["publisher_raw"].isna()]
print(f"{len(truly_missing)} titles still missing")
truly_missing[["title", "author"]]

37 titles still missing

                                                title              author
4                A Wizard’s Guide to Defensive Baking       T. Kingfisher
17                                      A Coup of Tea         Casey Blair
21            That Time I Got Drunk and Saved a Demon    Kimberly Lemming
27       Violet Thistlewaite Is Not a Villain Anymore  Emily Krempholtz\r
29                            A Pirate's Life for Tea      Rebecca Thorne
33                  The Undertaking of Hart and Mercy        Megan Bannen
37                       The Keeper of Magical Things         Julie Leong
39                               The Baby Dragon Café       Aamna Qureshi
40                     The Bookshop and the Barbarian        Morgan Stang
43                                    Forged by Magic    Jenna Wolfhart\r
45                            The Cybernetic Tea Shop       Meredith Katz
47                                          Mindtouch      M.C.A. Hogarth
51                                The Wizard's Butler       Nathan Lowell
54                                 House of Many Ways   Diana Wynne Jones
58                                   Magician's Hoard          Celia Lake
59                   Mr. Penumbra's 24-Hour Bookstore         Robin Sloan
60                         The Herbwitch's Apprentice          Ireen Chau
62                                 The Witching Flour     Samantha Silver
65                                            Fanuilh         Daniel Hood
69                                   Calculated Whisk     Lindsay Buroker
70                                      Drop of a Hat      Sara Bourgeois
71                              Tempests & Tea Leaves       Rachel Morgan
73                     Managing the Vampire's Mansion           K.M. Shea
74       Fates & Family: A Cozy Slice-of-Life Fantasy          Toni Binns
75               A Spot of Tea and Sorcery - Volume 1     Sylvia Mercedes
76               A Dragon Rider's Guide to Retirement          Julia Huni
77           The Remarkable Retirement of Edna Fisher       E.M. Anderson
79                                            Between     L.L. Starling\r
80                         A Prayer for the Crown-Shy      Becky Chambers
81                                     Small Miracles    Olivia Atwater\r
82                                    The Book of Zog         Alec Hutson
86                The Fairy Bargains of Prospect Hill      Rowenna Miller
91                               Chocolates and Claws        Claire Mavis
92               The Little Shop of Grand Curiosities           Iris Lake
93                                 Winterfrost Market     Jenny Sandiford
94  A Rival Most Vial: Potioneering for Love and P...        R.K. Ashwick
95                                  Beware of Chicken        CasualFarmer

In [28]:
import re

def simplify_title(title):
    simplified = re.sub(r"\(.*?\)", "", title)   # drop parenthetical series info
    simplified = simplified.split(":")[0]          # drop anything after a colon
    return simplified.strip()

for idx, row in truly_missing.iterrows():
    clean_title = simplify_title(row["title"])
    print(f"Trying: '{clean_title}' (original: '{row['title']}')")

Trying: 'A Wizard’s Guide to Defensive Baking' (original: 'A Wizard’s Guide to Defensive Baking')
Trying: 'A Coup of Tea' (original: 'A Coup of Tea')
Trying: 'That Time I Got Drunk and Saved a Demon' (original: 'That Time I Got Drunk and Saved a Demon')
Trying: 'Violet Thistlewaite Is Not a Villain Anymore' (original: 'Violet Thistlewaite Is Not a Villain Anymore')
Trying: 'A Pirate's Life for Tea' (original: 'A Pirate's Life for Tea')
Trying: 'The Undertaking of Hart and Mercy' (original: 'The Undertaking of Hart and Mercy')
Trying: 'The Keeper of Magical Things' (original: 'The Keeper of Magical Things')
Trying: 'The Baby Dragon Café' (original: 'The Baby Dragon Café')
Trying: 'The Bookshop and the Barbarian' (original: 'The Bookshop and the Barbarian')
Trying: 'Forged by Magic' (original: 'Forged by Magic')
Trying: 'The Cybernetic Tea Shop' (original: 'The Cybernetic Tea Shop')
Trying: 'Mindtouch' (original: 'Mindtouch')
Trying: 'The Wizard's Butler' (original: 'The Wizard's Butler')
Trying: 'House of Many Ways' (original: 'House of Many Ways')
Trying: 'Magician's Hoard' (original: 'Magician's Hoard')
Trying: 'Mr. Penumbra's 24-Hour Bookstore' (original: 'Mr. Penumbra's 24-Hour Bookstore')
Trying: 'The Herbwitch's Apprentice' (original: 'The Herbwitch's Apprentice')
Trying: 'The Witching Flour' (original: 'The Witching Flour')
Trying: 'Fanuilh' (original: 'Fanuilh')
Trying: 'Calculated Whisk' (original: 'Calculated Whisk')
Trying: 'Drop of a Hat' (original: 'Drop of a Hat')
Trying: 'Tempests & Tea Leaves' (original: 'Tempests & Tea Leaves')
Trying: 'Managing the Vampire's Mansion' (original: 'Managing the Vampire's Mansion')
Trying: 'Fates & Family' (original: 'Fates & Family: A Cozy Slice-of-Life Fantasy')
Trying: 'A Spot of Tea and Sorcery - Volume 1' (original: 'A Spot of Tea and Sorcery - Volume 1')
Trying: 'A Dragon Rider's Guide to Retirement' (original: 'A Dragon Rider's Guide to Retirement')
Trying: 'The Remarkable Retirement of Edna Fisher' (original: 'The Remarkable Retirement of Edna Fisher')
Trying: 'Between' (original: 'Between')
Trying: 'A Prayer for the Crown-Shy' (original: 'A Prayer for the Crown-Shy')
Trying: 'Small Miracles' (original: 'Small Miracles')
Trying: 'The Book of Zog' (original: 'The Book of Zog')
Trying: 'The Fairy Bargains of Prospect Hill' (original: 'The Fairy Bargains of Prospect Hill')
Trying: 'Chocolates and Claws' (original: 'Chocolates and Claws')
Trying: 'The Little Shop of Grand Curiosities' (original: 'The Little Shop of Grand Curiosities')
Trying: 'Winterfrost Market' (original: 'Winterfrost Market')
Trying: 'A Rival Most Vial' (original: 'A Rival Most Vial: Potioneering for Love and Profit')
Trying: 'Beware of Chicken' (original: 'Beware of Chicken')

In [29]:
def search_google_books_loose(title, timeout=10):
    url = "https://www.googleapis.com/books/v1/volumes"
    params = {"q": title, "key": API_KEY}
    response = requests.get(url, params=params, timeout=timeout)
    return response.json()

for idx, row in truly_missing.iterrows():
    clean_title = simplify_title(row["title"])
    data = search_google_books_loose(clean_title)
    if data.get("totalItems", 0) > 0:
        info = data["items"][0]["volumeInfo"]
        print(f"Original: {row['title']} | Author: {row['author']}")
        print(f"  → Found: {info.get('title')} | Publisher: {info.get('publisher')}")
        print("---")
    else:
        print(f"Still no match: {row['title']}")
    time.sleep(1)

Original: A Wizard’s Guide to Defensive Baking | Author: T. Kingfisher
  → Found: A Wizard's Guide to Defensive Baking | Publisher: None
---
Original: A Coup of Tea | Author: Casey Blair
  → Found: A Coup of Tea | Publisher: None
---
Original: That Time I Got Drunk and Saved a Demon | Author: Kimberly Lemming
  → Found: That Time I Got Drunk And Saved A Demon | Publisher: None
---
Original: Violet Thistlewaite Is Not a Villain Anymore | Author: Emily Krempholtz
  → Found: Violet Thistlewaite Is Not a Villain Anymore | Publisher: Penguin
---
Still no match: A Pirate's Life for Tea
Original: The Undertaking of Hart and Mercy | Author: Megan Bannen
  → Found: The Undertaking of Hart and Mercy | Publisher: Orbit
---
Still no match: The Keeper of Magical Things
Original: The Baby Dragon Café | Author: Aamna Qureshi
  → Found: The Baby Dragon Cafe (The Baby Dragon series) | Publisher: HarperCollins UK
---
Original: The Bookshop and the Barbarian | Author: Morgan Stang
  → Found: The Bookshop and the Barbarian | Publisher: None
---
Original: Forged by Magic | Author: Jenna Wolfhart
  → Found: Forged by Magic | Publisher: None
---
Still no match: The Cybernetic Tea Shop
Still no match: Mindtouch
Still no match: The Wizard's Butler
Still no match: House of Many Ways
Still no match: Magician's Hoard
Still no match: Mr. Penumbra's 24-Hour Bookstore
Still no match: The Herbwitch's Apprentice
Still no match: The Witching Flour
Original: Fanuilh | Author: Daniel Hood
  → Found: A Familiar Dragon | Publisher: None
---
Original: Calculated Whisk | Author: Lindsay Buroker
  → Found: A Calculated Whisk | Publisher: Beyond The Page
---
Still no match: Drop of a Hat
Still no match: Tempests & Tea Leaves
Original: Managing the Vampire's Mansion | Author: K.M. Shea
  → Found: Bewitch: A Steamy Forbidden Lovers Vampire / Witch Paranormal Romance | Publisher: Felicity Heaton Paranormal Romances
---
Still no match: Fates & Family: A Cozy Slice-of-Life Fantasy
Still no match: A Spot of Tea and Sorcery - Volume 1
Original: A Dragon Rider's Guide to Retirement | Author: Julia Huni
  → Found: A Dragon Rider's Guide to Retirement | Publisher: None
---
Original: The Remarkable Retirement of Edna Fisher | Author: E.M. Anderson
  → Found: The Remarkable Retirement of Edna Fisher | Publisher: None
---
Still no match: Between
Original: A Prayer for the Crown-Shy | Author: Becky Chambers
  → Found: A Prayer for the Crown-Shy | Publisher: Tordotcom
---
Still no match: Small Miracles
Still no match: The Book of Zog
Still no match: The Fairy Bargains of Prospect Hill
Still no match: Chocolates and Claws
Still no match: The Little Shop of Grand Curiosities
Still no match: Winterfrost Market
Original: A Rival Most Vial: Potioneering for Love and Profit | Author: R.K. Ashwick
  → Found: A Rival Most Vial | Publisher: None
---
Original: Beware of Chicken | Author: CasualFarmer
  → Found: Beware of Chicken 2 | Publisher: None
---

In [30]:
still_missing = metadata_df[metadata_df["publisher_raw"].isna()]
print(len(still_missing))
still_missing[["title", "author"]]

37

                                                title              author
4                A Wizard’s Guide to Defensive Baking       T. Kingfisher
17                                      A Coup of Tea         Casey Blair
21            That Time I Got Drunk and Saved a Demon    Kimberly Lemming
27       Violet Thistlewaite Is Not a Villain Anymore  Emily Krempholtz\r
29                            A Pirate's Life for Tea      Rebecca Thorne
33                  The Undertaking of Hart and Mercy        Megan Bannen
37                       The Keeper of Magical Things         Julie Leong
39                               The Baby Dragon Café       Aamna Qureshi
40                     The Bookshop and the Barbarian        Morgan Stang
43                                    Forged by Magic    Jenna Wolfhart\r
45                            The Cybernetic Tea Shop       Meredith Katz
47                                          Mindtouch      M.C.A. Hogarth
51                                The Wizard's Butler       Nathan Lowell
54                                 House of Many Ways   Diana Wynne Jones
58                                   Magician's Hoard          Celia Lake
59                   Mr. Penumbra's 24-Hour Bookstore         Robin Sloan
60                         The Herbwitch's Apprentice          Ireen Chau
62                                 The Witching Flour     Samantha Silver
65                                            Fanuilh         Daniel Hood
69                                   Calculated Whisk     Lindsay Buroker
70                                      Drop of a Hat      Sara Bourgeois
71                              Tempests & Tea Leaves       Rachel Morgan
73                     Managing the Vampire's Mansion           K.M. Shea
74       Fates & Family: A Cozy Slice-of-Life Fantasy          Toni Binns
75               A Spot of Tea and Sorcery - Volume 1     Sylvia Mercedes
76               A Dragon Rider's Guide to Retirement          Julia Huni
77           The Remarkable Retirement of Edna Fisher       E.M. Anderson
79                                            Between     L.L. Starling\r
80                         A Prayer for the Crown-Shy      Becky Chambers
81                                     Small Miracles    Olivia Atwater\r
82                                    The Book of Zog         Alec Hutson
86                The Fairy Bargains of Prospect Hill      Rowenna Miller
91                               Chocolates and Claws        Claire Mavis
92               The Little Shop of Grand Curiosities           Iris Lake
93                                 Winterfrost Market     Jenny Sandiford
94  A Rival Most Vial: Potioneering for Love and P...        R.K. Ashwick
95                                  Beware of Chicken        CasualFarmer

In [31]:
still_missing_now = metadata_df[metadata_df["publisher_raw"].isna()]
print(len(still_missing_now))
still_missing_now[["title", "author"]]

37

                                                title              author
4                A Wizard’s Guide to Defensive Baking       T. Kingfisher
17                                      A Coup of Tea         Casey Blair
21            That Time I Got Drunk and Saved a Demon    Kimberly Lemming
27       Violet Thistlewaite Is Not a Villain Anymore  Emily Krempholtz\r
29                            A Pirate's Life for Tea      Rebecca Thorne
33                  The Undertaking of Hart and Mercy        Megan Bannen
37                       The Keeper of Magical Things         Julie Leong
39                               The Baby Dragon Café       Aamna Qureshi
40                     The Bookshop and the Barbarian        Morgan Stang
43                                    Forged by Magic    Jenna Wolfhart\r
45                            The Cybernetic Tea Shop       Meredith Katz
47                                          Mindtouch      M.C.A. Hogarth
51                                The Wizard's Butler       Nathan Lowell
54                                 House of Many Ways   Diana Wynne Jones
58                                   Magician's Hoard          Celia Lake
59                   Mr. Penumbra's 24-Hour Bookstore         Robin Sloan
60                         The Herbwitch's Apprentice          Ireen Chau
62                                 The Witching Flour     Samantha Silver
65                                            Fanuilh         Daniel Hood
69                                   Calculated Whisk     Lindsay Buroker
70                                      Drop of a Hat      Sara Bourgeois
71                              Tempests & Tea Leaves       Rachel Morgan
73                     Managing the Vampire's Mansion           K.M. Shea
74       Fates & Family: A Cozy Slice-of-Life Fantasy          Toni Binns
75               A Spot of Tea and Sorcery - Volume 1     Sylvia Mercedes
76               A Dragon Rider's Guide to Retirement          Julia Huni
77           The Remarkable Retirement of Edna Fisher       E.M. Anderson
79                                            Between     L.L. Starling\r
80                         A Prayer for the Crown-Shy      Becky Chambers
81                                     Small Miracles    Olivia Atwater\r
82                                    The Book of Zog         Alec Hutson
86                The Fairy Bargains of Prospect Hill      Rowenna Miller
91                               Chocolates and Claws        Claire Mavis
92               The Little Shop of Grand Curiosities           Iris Lake
93                                 Winterfrost Market     Jenny Sandiford
94  A Rival Most Vial: Potioneering for Love and P...        R.K. Ashwick
95                                  Beware of Chicken        CasualFarmer

In [32]:
metadata_df.to_csv("../clean/cozy_fantasy_corpus.csv", index=False)

In [35]:
#re-upload manually completed dataset
metadata_df = pd.read_csv("../raw/raw_title_list - cozy_fantasy_pub_cats.csv")
metadata_df["pub_category"].value_counts()

pub_category
traditional       64
self-published    35
Name: count, dtype: int64